"""initial contact_requests

Revision ID: 248c20c9b1de
Revises: 
Create Date: 2026-06-20 15:42:41.441803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '248c20c9b1de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('ai_sentiment', sa.String(length=16), nullable=True),
    sa.Column('ai_category', sa.String(length=32), nullable=True),
    sa.Column('ai_priority', sa.String(length=16), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_reply', sa.Text(), nullable=True),
    sa.Column('ai_provider', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_requests_created_at'), 'contact_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_contact_requests_email'), 'contact_requests', ['email'], unique=False)
    op.create_index(op.f('ix_contact_requests_ip_address'), 'contact_requests', ['ip_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_requests_ip_address'), table_name='contact_requests')
    op.drop_index(op.f('ix_contact_requests_email'), table_name='contact_requests')
    op.drop_index(op.f('ix_contact_requests_created_at'), table_name='contact_requests')
    op.drop_table('contact_requests')
    # ### end Alembic commands ###
